### ISSUE TITLE
unexpected output when dict key contains a '/' with reducer='path' options

### ISSUE THREAD

**Issue by liozzazhang** [ianlini/flatten-dict#10]

**Comment by liozzazhang** [comment]
example dict:
`ingress:
  enabled: enable
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/redirect-entry-point: https`
when it is flattened, the result is:
`ingress/enabled enable`
...
`ingress/annotations/traefik.ingress.kubernetes.io/redirect-entry-point enable`
In the last line, the flattened key level is 4 while the original key level is 3. That's the problem.

Thanks,
Lizzano

**Comment by ianlini** [comment]
If the keys are a folder structure, then `ingress/annotations/traefik.ingress.kubernetes.io/redirect-entry-point` is the expected result because it's the most concise representation of that path.

The question is actually: what is the expected result you want?

**Comment by liozzazhang** [comment]
If i need to resolve the above result back to dict format. The result will be 
```
ingress:
  annotations:
    traefik.ingress.kubernetes.io:
      redirect-entry-point: https
```
That's not what i expect. Also, such situation happens when I continue to operate after dict flattened. For example, i usually write flattened kv pairs to consul server.

Is there any mark that can diff the '/' between folder structure and dict key?

**Comment by liozzazhang** [comment]
This is not a bug. I will appreciate it if you can improve it. Thanks.

**Comment by ianlini** [comment]
Sorry, I'm not familiar with Consul, but now I know that the problem is actually about the reversibility.

Yes, by design, `flatten()` sometimes is irreversible.
It's impossible to make flattening a "path" reversible when a key contains `/`.
The reason is that most file systems don't accept `/` as a part of a filename or directory name:
https://stackoverflow.com/questions/9847288/is-it-possible-to-use-in-a-filename
There is no standard way to escape `/` in a path.

The solution may be:
1. Use another character to replace `/` in your key, but you actually shouldn't use `path` reducer if you are not actually dealing with path. `os.path.join()` is for cross-platform path joining, so there should be some behavior you don't expect.
2. You can choose another separator and write customized reducer and splitter functions. You also should ensure that the separator shouldn't appear in any key.
3. Change the way you serialize the flattened key.
One way is to use `tuple` (default) reducer to flatten the dict, and serialize the tuple to json, pickle or whatever reversible format.

**Comment by ianlini** [comment]
#16 may make the 2nd solution easier.
