### ISSUE TITLE
Feature Proposition: Underscores as native separators

### ISSUE THREAD

**Issue by duarteocarmo** [ianlini/flatten-dict#11]
Hey there!

Can I make a pull request for native inclusion of the underscores as a separator? 

Something like: 

`
flatten(normal_dict, reducer="_")
`

which would output the expanded dict with underscores as separators directly. 

What do you think? 

Cheers and thanks for a great little utility 😄

**Comment by ianlini** [comment]
Sure. PRs are welcome :smile:.

I prefer using `underscore` as its name because it's more explicit.
For examples:
```
flatten(d, reducer='underscore')
unflatten(d, splitter='underscore')
```

You can simply copy the `underscore_splitter` and `underscore_reducer` functions from the examples in README.
I actually didn't think there is a useful use case for underscore, so I only put it in the examples.
If you think it's useful, then we should add it.

Thanks for the contribution!

**Comment by duarteocarmo** [comment]
Great, I'll get one done before end of week!

When un-nesting a giant json to feed it into something like a pandas dataframe its very useful. At least in my case 🙈 

I'll have a PR soon 😄

**Comment by duarteocarmo** [comment]
Having trouble reproducing tests. Do you want to walk me through your setup please?

**Comment by duarteocarmo** [comment]
Forget it, didn't know about node. Now I do :smile:
