### ISSUE TITLE
Path reducer fails when enumerate_types contains 'list'

### ISSUE THREAD

**Issue by marcsello** [ianlini/flatten-dict#23]
The flatten method fails to flatten lists with path reducer if the input data contains list, and enumerating lists is enabled.

Simple code to reporduce:
```python
from flatten_dict import flatten

data = {
	"fruits" : ['apple','mango','kiwi']
}

flatten(data,reducer="path",enumerate_types=(list,))
```
Produces the following output:
```
Traceback (most recent call last):
  File "repr.py", line 7, in <module>
    flatten(data,reducer="path",enumerate_types=(list,))
  File "/home/marcsello/mmvmm2/venv/lib/python3.7/site-packages/flatten_dict/flatten_dict.py", line 88, in flatten
    _flatten(d)
  File "/home/marcsello/mmvmm2/venv/lib/python3.7/site-packages/flatten_dict/flatten_dict.py", line 75, in _flatten
    _flatten(value, flat_key)
  File "/home/marcsello/mmvmm2/venv/lib/python3.7/site-packages/flatten_dict/flatten_dict.py", line 71, in _flatten
    flat_key = reducer(parent, key)
  File "/home/marcsello/mmvmm2/venv/lib/python3.7/site-packages/flatten_dict/reducer.py", line 13, in path_reducer
    return os.path.join(k1, k2)
  File "/usr/lib/python3.7/posixpath.py", line 94, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.7/genericpath.py", line 149, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'int'
```
As I have investigated, I have found, that this may caused by that path reducer relies on python's internal path.join method, which fails when a number is passed to it. The enumeration passes a number to the join function, so this causes it to fail.

**Comment by ianlini** [comment]
That's why the reducer is called `path_reducer`. I agree that sometimes it will be more convenient to convert other types to str automatically. However, when we say we want to form a path with some components, the only choices in Python are `os.path.join` and `pathlib.Path`. All the related functions accept str only, so it's quite intuitive that you shouldn't join 2 non-str variables when we use the name `path_reducer`.

I think it would be better to provide another non-default option to do the type conversion. I will design for this soon.

**Comment by ianlini** [comment]
After 0.3.0, you can do this:
```python
>>> from flatten_dict import flatten
>>> from flatten_dict.reducer import make_reducer
>>> data = {"fruits": ["apple", "mango", "kiwi"]}
>>> flatten(data, reducer=make_reducer("/"), enumerate_types=(list,))
{'fruits/0': 'apple', 'fruits/1': 'mango', 'fruits/2': 'kiwi'}
```
